name = "Nguhcraft"
author = "Ætérnal"
version = "1.33.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fb7981e89ccbbc8b91d595922d3e4c283b65fcf4ac5c6d508e01a4a1aa83616"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"

[options]
acceptable-game-versions = ["1.21.7"]
